import "@/assets/styles/main.scss";
import Header from "@/components/Header";
import PageWrapper from "@/components/PageWrapper";
import Footer from "@/components/Footer";
import projects from "@/config";
import { circleAnimations } from "@/utils/animations";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

var circleStyles = {
  "/": {
    color: "rgba(255,137,0,0.75)",
    animation: circleAnimations.circleMoveHome,
  },
  "/works": {
    color: "rgba(255,116,143,0.75)",
    animation: circleAnimations.circleMoveWorks,
  },
  "/about": {
    color: "rgba(98,255,0, 0.5)",
    animation: circleAnimations.circleMoveAbout,
    scale: true,
  },
  "/contact": {
    color: "rgba(10,140,143, 0.75)",
    animation: circleAnimations.circleMoveContact,
  },
  "/music": {
    color: "rgba(10,140,143, 0.75)",
    animation: circleAnimations.circleMoveContact,
  },
};

for (const project of projects.default) {
  circleStyles[`/works/${project.slug}`] = {
    color: project.accentColor,
    animation: {
      xs: project.circleStyle.xs,
      sm: project.circleStyle.xs,
      md: project.circleStyle.xs,
      lg: project.circleStyle.xs,
      xl: project.circleStyle.xl,
      xxl: project.circleStyle.xl,
    },
    scale: true,
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/hke5bry.css" />
      </head>
      <body>
        <div className="layout-default">
          <Header />
          <PageWrapper circleStyles={circleStyles}>{children}</PageWrapper>
          {/* <Footer /> */}
        </div>
      </body>
    </html>
  );
}
